[package]
name = "darkestdev/struktura"
description = "Luau strict-typed Framework (ft. Blink, VoidSentry, LemonSignal)"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["Def.blink", "rokit.toml", "selene.toml"]

[dependencies]
Promise = "evaera/promise@^4"
VoidSentry = "elentium/voidsentry@0.0.7"
LemonSignal = "data-oriented-house/lemonsignal@1.11.0"